; crub
; wisncn@aol.com
; github.com/wisnc
; 2026-05-14

[env:bootloader]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = espidf
board_build.partitions = partitions.csv
build_flags =
    -DESP32S3

[env:m5cardputer]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = partitions.csv
board_upload.maximum_size = 786432
lib_deps =
    https://github.com/m5stack/M5Cardputer.git#e023280
build_flags =
    -DESP32S3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM=0
monitor_speed = 115200
upload_speed = 1500000
